---
title: ""
---

&nbsp; &nbsp;

I'm **David Causeur**, full professor of statistics

in the Department of Statistics and Computer Science,

at [Institut Agro](https://www.institut-agro-rennes-angers.fr/), Rennes, France.

I'm a research fellow at [IRMAR, UMR 6625 CNRS](https://irmar.univ-rennes1.fr/)

I'm the current President of the [French region](https://sfb.pages.math.cnrs.fr/asso/) of the [International Biometric Society](https://www.biometricsociety.org/home).

For more check out my [resume](DC-CV_short.pdf).

Contact me by [email].

[email]: mailto:david.causeur@agrocampus-ouest.fr

## Job offer

[6-month internship (master thesis)](Offre_de_stage_M2_EpiPredict.pdf)

## Upcoming conferences

* June 29 - July 1, 2022 [Intelligence artificielle et santé : approches interdisciplinaires](https://www.lebesgue.fr/fr/conf_IA_sante2022)
* July 10-15, 2022, [31st International Biometric Conference](https://www.ibc2022.org/home)
* October 20-21, 2022, [Emerging challenges in implementing the exposome](https://exposomesymposium.org/)
* December 8-9, 2022, [DIGIT-BIO seminar](https://www6.inrae.fr/digitbio/Page-d-accueil/Actualites/DIGIT-BIO-vous-invite-a-son-1er-seminaire-a-Lyon-les-8-et-9-decembre)
* December 17-19, 2022, [15th International Conference of the ERCIM WG on Computational and Methodological Statistics (CMStatistics2022)](http://www.cmstatistics.org/CMStatistics2022/publications.php)
* January, 19, 2023, [Journée Jeunes Chercheur.e.s de la SFB](https://sfb-jjc2023.sciencesconf.org), L'Institut Agro Rennes Angers, Rennes.
* July 3-7, 2023, JdS2023, 54èmes Journées de Statistique de la SFdS, Université Libre de Bruxelles, Belgique.