---
title: "Analyse des données avec R"
subtitle: "10, 11 et 13 janvier 2022 - La Boulangère"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

&nbsp;

**Objectifs**: 

* Acquérir une autonomie dans la mise en oeuvre de
démarches d'analyse adaptées à différentes
problématiques rencontrées en situation professionnelle
* Mettre en oeuvre ces démarches d'analyse dans R et Rstudio
* Editer des rapports d'analyse de données avec Rmarkdown

**Organisation de la session**: La formation est divisée en trois parties se déclinant autour de la question *y-a t'il un effet de ceci sur cela ?* : 

* *Explorer, manipuler, visualiser des données* : cette première étape vise a orienter la synthèse de données vers la vérification ou la recherche d'hypothèses de travail sur le lien supposé entre *ceci* et *cela*  ;
* *Tester* : l'objectif est ici de confronter une hypothèse de travail aux données pour affirmer finalement que *cela* dépend effectivement de *ceci* (ou non) ; 
* *Prédire* : cette dernière partie pose le problème de la prédiction à partir de tous les effets identifiés comme intéressants. Elle introduit quelques méthodes d'apprentissage statistique pour aborder des situations d'analyse de données en grande dimension.

L'ensemble de la formation insiste moins sur les aspects formels et mathématiques des méthodes présentées que sur la confrontation à des situations pratiques et sur les recommandations en matière de choix d'une méthode. 

L'environnement R et l'interface de développement Rstudio sont choisis pour construire ces compétences. L'édition de rapports d'analyse de données par l'utilisation de Rmarkdown est également présentée.  

## Partie 1

* [Présentation](./teaching/html/slides_FC_fruit_Part_1.html) 
* [Données](./teaching/data/FC/maturity.txt)
* [Rmd script](./teaching/scripts/Part1.Rmd)   

## Partie 2

* [Présentation](./teaching/html/slides_FC_fruit_Part_2.html) 
* [Données](./teaching/data/FC/maturity.txt)
* [Rmd script](./teaching/scripts/Part2.Rmd)   

## Partie 3

* [Présentation](./teaching/html/slides_FC_fruit_Part_3.html) 
* [Données](./teaching/data/FC/maturity_nirs.txt)
* [Rmd script](./teaching/scripts/Part3.Rmd) 
