---
title: "First steps in data analysis with R"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

*Course objective*: Introducing basic statistical methods for assessing and visualizing effects of explanatory variables on responses (linear model, Principal Component Analysis and Design of experiments). 

*Organization*: The course is divided into eight sessions. Each session is made of a lecture and (at least) two practical classes. In those in-class practical classes, students are given the opportunity to tackle problem-solving exercises, with or without the use of R.  

The following documents are provided for each session:

* a 1h-video lecture: a R tutorial whose slides, data and R script are provided (only for sessions 1 to 5);   
* a PDF file containing a self-directed learning exercise; 
* two PDF files with in-class exercises.  

All in-class activities (practical sessions) [here](https://agrocampusds.github.io/demarche_statistique/).

Examples of recent examination: 

* [exam](./teaching/PDFs/DS21examSession1.pdf) 
* [exam](./teaching/PDFs/DS_Exercice_Souche.pdf), [data](./teaching/data/souche.txt)

Examination 2024 - 1st session : [exam](./teaching/PDFs/ExamDS20241.pdf), [data](./teaching/data/hedo-sucre.txt)

Assignments: see instructions [here](./teaching/PDFs/evaluation.pdf).

## Session 1

*Objective*: Introducing the principles of statistical inference and especially hypothesis testing. What does the question "Is there an effect of this on that?" mean in practice? 

* [Video lecture](https://youtu.be/vHiRSJGq53M) with [slides](./teaching/PDFs/DS20Session1.pdf), [data](./teaching/data/pig.txt) and [R script](./teaching/scripts/session1.R);   
* Self-directed learning [exercise](./teaching/pdfs/ds20exerciceautoevaluation1.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/Scripts/ExerciceAutoEvaluation1.R); 

## Session 2

*Objective*: Introducing the F-test for the group mean comparison.

* [Video lecture](https://youtu.be/cGkuIZM_-AE) with [slides](./teaching/PDFs/DS20Session2.pdf), [data](./teaching/data/pig.txt) and [R script](./teaching/scripts/session2.R);   
* Self-directed learning [exercise](./teaching/pdfs/ds20exerciceautoevaluation2.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/scripts/exerciceautoevaluation2.R);

## Session 3

*Objective*: Introducing the t-test for the two-group mean comparison, the power of a t-test, the Bonferroni correction for the multiplicity of simultaneous tests.

* [Video lecture](https://youtu.be/5GrlbSspeic) with [slides](./teaching/PDFs/DS20Session3.pdf), [data](./teaching/data/pig.txt) and [R script](./teaching/scripts/session3.R);   
* Self-directed learning [exercise](./teaching/pdfs/ds20exerciceautoevaluation3.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/scripts/exerciceautoevaluation3.R);

## Session 4

*Objective*: Introducing the paired t-test for the two-group mean comparison and the simple linear regression model.

* [Video lecture](https://youtu.be/r6evkckZ1y8) with [slides](./teaching/PDFs/DS20Session4.pdf), [data](./teaching/data/pig.txt) and [R script](./teaching/scripts/session4.R);   
* Self-directed learning [exercise](./teaching/pdfs/ds20exerciceautoevaluation4.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/scripts/exerciceautoevaluation4.R);

## Session 5

*Objective*: Introducing the F-test in the simple linear regression model and the prediction issue. The lecture ends with the implementation of an F-test to conclude about group differences between linear effects (an example of interaction effect).

* [Video lecture](https://youtu.be/tV7H3tpJvsQ) with [slides](./teaching/PDFs/DS20Session5.pdf), [data](./teaching/data/pig.txt) and [R script](./teaching/scripts/session5.R);   
* Self-directed learning [exercise](./teaching/pdfs/ds20exerciceautoevaluation5.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/scripts/exerciceautoevaluation5.R);

## Session 6

*Objective*: Choosing the explanatory variables to be included in a linear model, when the issue focuses on a particular effect of interest (with possibly confusing or interaction effects) or, on the contrary, when all explanatory variables are equivalently candidate to enter the model (model selection, information criterion).

* [slides](./teaching/PDFs/DS25Session6.pdf), [data](./teaching/data/pig10.txt) and [R script](./teaching/scripts/Session6.R);   
* Self-directed learning [exercise](./teaching/pdfs/Exerciceautoevaluation6.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/scripts/exerciceautoevaluation5.R);

## Session 7

*Objective*: describing multivariate profiles by a limited number of latent scores (Principal Component Analysis).

* [slides](./teaching/PDFs/DS25Session7.pdf), [data](./teaching/data/pig10.txt) and [R script](./teaching/scripts/Session7.R);   
* Self-directed learning [exercise](./teaching/pdfs/Exerciceautoevaluation7.pdf), [data](./teaching/data/coffee.txt) and [R script](./teaching/scripts/exerciceautoevaluation5.R);

## Session 8

*Objective*: introducing the basic principles of experimental designs (fractional factorial designs).

* [slides](./teaching/PDFs/DS25Session8.pdf) and [R script](./teaching/scripts/Session8.R);   
* Self-directed learning [exercise](./teaching/pdfs/Exerciceautoevaluation8.pdf);