---
title: "Courses"
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE} 
library(fontawesome)
```

All courses take the form of `r fa("r-project", fill = "dodgerblue")` tutorials. Statistical methods and concepts are motivated by illustrative situations in a large scope of applications in life sciences. Basic functions in R are introduced to implement those methods. 

## **Current courses**

 `r fa("pencil-alt", fill = "dodgerblue")` [First steps in data analysis with R](firststeps.html)

 **Short description**: The course introduces the basics of inferential statistics. It essentially provides tools to answer the question "Is there an effect of *this* on *that*?" using data. The scope of statistical methods in the course is limited to common variants of the former question: "Are there differences across group means of *that*?" and "Is there a linear relationship between *this* and *that*?".
 
 **Keywords**: Hypothesis testing, Estimation, One-way Analysis of variance, F-test, t-test, Simple linear regression model
 
 `r fa("pencil-alt", fill = "dodgerblue")` [Statistics for decision making](statdecision.html)
 
 **Short description**: In many situations, especially in biological applications, data analysis aims at understanding why some profiles have a higher probability than others to belong to a class of interest. Typically, which clinical profiles are more likely to be affected by a disease? The course introduces statistical models to answer such questions and the following sub-questions: Does a covariate significantly explain variations between class probabilities? How to select a minimal and sufficient subset of covariates explaining the variations between class probabilities? How to use a profile of covariates to predict the membership to a given class?
 
 **Keywords**: Logistic linear regression model, Analysis of deviance testing, AIC, BIC, Classification errors.
 
 `r fa("pencil-alt", fill = "forestgreen")` [Genomic data analysis](genomicdata.html)
 
 **Short description**: In molecular biology, genomics aims at understanding how the genome works using whole-genome measurements obtained by high-throughput biotechnology. Analyzing those massive data raises many specific statistical issues. The most common of those issues are addressed in this introductory course.  
 
 `r fa("pencil-alt", fill = "forestgreen")` [High-dimensional regression and classification modeling for biological data analysis](statlearnbiodata.html)
 
 **Short description**: High-throughput technology (imaging, spectroscopy, etc.) is now currently used for many biological applications. Using high-dimensional data generated by those technology to make prediction rules require ad-hoc methods. The most commonly used of these methods are introduced in the course.
 
## **Past courses**

 `r fa("pencil-alt", fill = "forestgreen")` Introduction to geostatistics.
 
 **Short description**: The course introduces the prediction issue with geolocalized data (kriging) using a spatial stationary dependence model (variogram modeling). [Slides](./teaching/PDFs/Geoslides.pdf), [R script](./teaching/Scripts/Geoscript.R), [Data](./teaching/data/Geodata.txt) and [Handbook](./teaching/PDFs/GeoHandbook.pdf). 

 `r fa("pencil-alt", fill = "forestgreen")` Introduction to biomathematics.
 
 **Short description**: The purpose of the course is to introduce basic mathematical concepts motivated by biological modeling applications. [Functional analysis slides](./teaching/PDFs/biomathsslides.pdf), [Enzyme kinetics](./teaching/PDFs/EnzymeSlides.pdf).